# Generated by Django 2.0.3 on 2018-03-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_manager', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=20)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
