# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BandName', models.CharField(max_length=250)),
                ('Manager', models.CharField(max_length=250)),
                ('ContactNumber', models.IntegerField(max_length=250)),
                ('ContactEmail', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
            ],
        ),
    ]
