# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_auto_20180308_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ContactEmail',
            field=models.EmailField(max_length=250),
        ),
    ]
