# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_auto_20180308_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='BandName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='ContactEmail',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Manager',
            field=models.CharField(max_length=20),
        ),
    ]
