# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0004_auto_20180309_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=5)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('StreetAddress', models.CharField(max_length=20)),
                ('PostalCode', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('CountryCode', models.CharField(max_length=20)),
                ('TicketsBought', models.CharField(max_length=20)),
            ],
        ),
    ]
