# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0005_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='PostalCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='StreetAddress',
            field=models.CharField(max_length=50),
        ),
    ]
