# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0006_auto_20180309_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='ARTISTS',
        ),
    ]
